### ISSUE TITLE
Endian type check

### ISSUE THREAD

**Issue by Ghostwalker71** [niftools/pyffi#20]
Adding endian type check to num uv sets as  seen in nif xml pull req - **Particle system + 20.3.0.9 support** - commit - **Extended support for 20.3.0.9** causes pyffi to return a missing attribute error during import within blender.

**Comment by neomonkeus** [comment]
Can you upload the stacktrace from the error.

**Comment by Ghostwalker71** [comment]
I have since rearranged the file structure and made numerous edits to my pyffi repo, so it wouldn't be a valid stack. the pull for the xml can be easily merged with the current develop branch in the niftools repo. The conflicts were minor.

**Comment by neomonkeus** [comment]
Reference niftools/nifxml#40
