### ISSUE TITLE
Release 2.2.3 (and older than 2.2.2) not on pypi

### ISSUE THREAD

**Issue by psi29a** [niftools/pyffi#26]
I know that when we make releases on github (tag), it will not retrieve files from submodules. That makes installation with pip3 impossible as it doesn't include the nif.xml submodule.

Can someone upload 2.2.3 to PyPi? Also, can someone also upload older packages?

If we need help here, I can help as I also manage PyPi packages: 
https://pypi.org/user/psi29a/

We should offer older packages as well, for example 2.1.x isn't on PyPi which is problematic for those still using Python 2.6 or Python 2.7 (see Blender 2.49b).

**Comment by neomonkeus** [comment]
Pyffi on pypi was not actually released under niftools, it was originally release by the original maintainer @amorilia. They are on long term sabbatical, to the point where any projects that were originally forked, have been completely disconnected. 

Need weigh in amount of effort having to maintain another server. Having it pull from a remote rather than just being bundled. Is the intention for users or developers, etc.

**Comment by psi29a** [comment]
I've had the same problem with PyPI with a project of mine being hosted by a developer that was long gone. I filed a report, waited the amounted time for pypi devs to contact the  maintainer and after that expired, they made me maintainer.  Example: https://pypi.python.org/pypi/txmongo

We can propose the same, this time adding you and others necessary to be maintainers of the pypi page. That way we can retain the name.

Want me to do this?

**Comment by neomonkeus** [comment]
I suppose we need to talk about other issues as well first before making a decision.

1. what else could be/should made available as part of the org.
2. Admin : Responsibility of releases, can we have an org representative

**Comment by psi29a** [comment]
Of course, who are all the people currently active and non-active involved with PyFFI?

As for your list:

1. PyPI is just a way to host python packages. So each package has its own page where you can upload releases to for consumption. I would not recommend this for the blender nif plugin for example, but only for PyFFI since it is a standalone package.

2. There can be more than one person as 'owner' of the PyPI entry, as a matter of fact, I recommend at least 2 but prefer 3 some-what active people. The extra one being someone not really involved with PyFFI directly but active with Niftools in general.

Considering that releases are few and far in between, it is a trivial amount of work to make releases and upload them. 

With what is available on PyPI, we can roll later binary releases like for windows.

I can help with all of this if you these.

**Comment by TagnumElite** [comment]
There is the possibility of automated uploads to PyPi using Travis.

I have it setup [here](https://github.com/TagnumElite/yummy_sphinx_theme/blob/develop/.travis.yml#L30).
[Travis Documentation](https://docs.travis-ci.com/user/deployment/pypi/)

The way I setup it up is when ever the master branch on the main repo is updated it will try to deploy only on the python 3.6 build (_That way traivs doesn't try uploading the build 4 times._).
The filters for delpoying:
- GitHub Branch: `master` Only on master branch commit
- Python Version: `3.6` Only on python 3.6 build
- GitHub Repo: `TagnumElite/yummy_sphinx_theme` The commit must come from the main repo.

**Comment by neomonkeus** [comment]
Additional thoughts
- Merge to master, full release with tags, update revision.
- merge to develop branch build a dev preview release, override existing "dev" release.
- possible nightly branch, force push to to make it accessible to people.

**Comment by psi29a** [comment]
We're are still not the maintainers of the pypi repo... we've asked for access, but no one has looked at our ticket.

**Comment by TagnumElite** [comment]
I would recommend making an [Issue here](https://github.com/pypa/pypi-legacy/issues?q=is%3Aissue+is%3Aopen+label%3Apackage-claim)

**Comment by psi29a** [comment]
Does that work?  ;)

I'll copy paste what I wrote here (because it worked with other packages I've recovered)
https://sourceforge.net/p/pypi/support-requests/707/

**Comment by psi29a** [comment]
https://github.com/pypa/pypi-legacy/issues/750

Help put some heat on it by liking it.

**Comment by neomonkeus** [comment]
@psi29a Got access :+1:

**Comment by psi29a** [comment]
Super, add me too (for redundancy) as a maintainer?

**Comment by neomonkeus** [comment]
All of the releases are on pypi, just not visible. I have put 2.2.3 up on pypi, but will be re-uploading a new version once #54 is resolved and will close this off then.

**Comment by neomonkeus** [comment]
Uploaded latest build to pypi so closing
