### ISSUE TITLE
Github PR & Issue Template 

### ISSUE THREAD

**Issue by neomonkeus** [niftools/pyffi#28]
To make it easier for people creating PRs or Issue, we can upload a template.
This will help keep things uniform, in terms of what we want to be provided for a PR/Issue to be accepted

See : niftools/blender_nif_plugin/issues/231

**Comment by neomonkeus** [comment]
@psi29a - Any input on what sections would be useful would be appreciated

**Comment by psi29a** [comment]
Something involving tests
 - added new tests and coverage to existing code
 - added feature with test

Normally I try to encourage people who contribute to also write unit-tests for their changes, when appropriate.

**Comment by neomonkeus** [comment]
This is a cut down version of the blender template for issues.

# Context
[provide more detailed introduction to the issue itself and why it is relevant]

# Steps to Reproduce
[ordered list the process to finding and recreating the issue]

# Expected result
[describe what you would expect to have resulted from this process]

# Current result
[describe what you you currently experience from this process, and thereby explain the bug]

# Possible Fix
[not obligatory, but suggest fixes or reasons for the bug]

# Logs and Files
[provide links to logs file generated during the error, generated input and output files you were using at the time]

Additional Information
[anything else you feel is relevant]

**Comment by neomonkeus** [comment]
Closed by #34
